apiVersion: apps/v1
kind: Deployment
metadata:
  name: DevOpsTask-CICD
  labels:
    app: DevOpsTask-CICD
spec:
  replicas: 1
  selector:
    matchLabels:
      app: DevOpsTask-CICD
  template:
    metadata:
      labels:
        app: DevOpsTask-CICD
    spec:
      containers:
        - name: DevOpsTask-CICD
          image: 274127640471.dkr.ecr.us-east-2.amazonaws.com/DevOpsTask-CICD:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
