name: Node js app deploy to EKS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code manually
      run: |
        git init
        git remote add origin https://github.com/${{ github.repository }}.git
        git fetch origin
        git checkout ${{ github.ref_name }}

    - name: Install kubectl manually
      run: |
        curl -LO "https://dl.k8s.io/release/v1.24.0/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/

    - name: Install eksctl
      run: |
        curl --silent --location "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
        sudo mv /tmp/eksctl /usr/local/bin

    - name: Configure AWS Credentials
      run: |
        mkdir -p ~/.aws
        echo "[default]" > ~/.aws/credentials
        echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
        echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
        echo "[default]" > ~/.aws/config
        echo "region = ap-south-1" >> ~/.aws/config

    - name: Create ECR repository if not exists
      run: |
        aws ecr describe-repositories --repository-names devopstask-cicd --region ap-south-1 || \
        aws ecr create-repository --repository-name devopstask-cicd --region ap-south-1

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region ap-south-1 | \
        docker login --username AWS --password-stdin 034362074714.dkr.ecr.ap-south-1.amazonaws.com

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: 034362074714.dkr.ecr.ap-south-1.amazonaws.com
        REPOSITORY: devopstask-cicd
        IMAGE_TAG: 1.1
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

    - name: Create EKS Cluster if not exists
      run: |
        eksctl get cluster --region ap-south-1 --name DevOpsTask-CICD || \
        eksctl create cluster \
          --name DevOpsTask-CICD \
          --region ap-south-1 \
          --nodes 2 \
          --node-type t3.medium \
          --with-oidc \
          --managed

    - name: Update kube config
      run: aws eks update-kubeconfig --name DevOpsTask-CICD --region ap-south-1

    - name: Deploy to EKS
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
